# tests/test_opencode_config.py
"""_write_opencode_config must hand the opencode brain a working MCP
declaration: JARVIS's own tools under an undisplaceable `jarvis` entry,
plus the user's own declared servers translated into opencode's shape —
with the same validation the mcp.json writer applies, and the same URL
that actually reaches the running server.
"""
import json
import os

import pytest


@pytest.fixture
def server_module(monkeypatch, tmp_path):
    monkeypatch.setenv("JARVIS_DATA_DIR", str(tmp_path))
    import importlib
    import server as server_module
    importlib.reload(server_module)
    return server_module


def _write(server_module, monkeypatch, tmp_path, connections=None,
           scheme="http", bind_host="127.0.0.1", port="8340"):
    monkeypatch.setenv("JARVIS_SCHEME", scheme)
    monkeypatch.setenv("JARVIS_BIND_HOST", bind_host)
    monkeypatch.setenv("JARVIS_PORT", str(port))
    if connections is not None:
        import data_paths
        data_paths.ensure_brain_home()
        data_paths.connections_path().write_text(
            json.dumps({"mcpServers": connections}), encoding="utf-8")
    home = tmp_path / "home"
    home.mkdir(exist_ok=True)
    return server_module._write_opencode_config(home)


def _jarvis(config):
    entry = config["mcp"]["servers"]["jarvis"]
    assert entry["type"] == "local"
    return entry


def test_jarvis_entry_points_at_the_tool_endpoint(server_module, monkeypatch,
                                                  tmp_path):
    path = _write(server_module, monkeypatch, tmp_path,
                  scheme="https", bind_host="::1", port="8341")
    config = json.loads(path.read_text(encoding="utf-8"))
    entry = _jarvis(config)
    assert entry["command"][0].lower().endswith("python.exe") or \
        entry["command"][0].endswith("python")
    assert entry["command"][1].endswith("jarvis_mcp.py")
    assert entry["environment"]["JARVIS_TOOL_URL"] == \
        "https://[::1]:8341/internal/tool"
    assert entry["environment"]["JARVIS_TOOL_TOKEN_FILE"].endswith(
        "tool-token")


def test_jarvis_entry_cannot_be_displaced(server_module, monkeypatch,
                                          tmp_path):
    path = _write(server_module, monkeypatch, tmp_path, connections={
        "jarvis": {"command": "evil", "args": ["--takeover"]}})
    config = json.loads(path.read_text(encoding="utf-8"))
    entry = _jarvis(config)
    assert "evil" not in " ".join(entry["command"])
    problems = " ".join(server_module.LAST_CONNECTIONS.problems)
    assert "jarvis" in problems


def test_local_user_server_is_translated_verbatim(server_module, monkeypatch,
                                                  tmp_path):
    path = _write(server_module, monkeypatch, tmp_path, connections={
        "notes": {"command": "C:\\Tools\\notes mcp.exe",
                  "args": ["--stdio"],
                  "environment": {"NOTES_TOKEN": "s3cret"}}})
    entry = json.loads(path.read_text(encoding="utf-8"))["mcp"]["servers"][
        "notes"]
    assert entry == {
        "type": "local",
        "command": ["C:\\Tools\\notes mcp.exe", "--stdio"],
        "environment": {"NOTES_TOKEN": "s3cret"},
    }


def test_remote_user_server_is_translated(server_module, monkeypatch,
                                          tmp_path):
    path = _write(server_module, monkeypatch, tmp_path, connections={
        "docs": {"url": "https://mcp.example.com/mcp"}})
    entry = json.loads(path.read_text(encoding="utf-8"))["mcp"]["servers"][
        "docs"]
    assert entry == {"type": "remote", "url": "https://mcp.example.com/mcp"}


def test_invalid_entries_are_reported_and_left_out(server_module, monkeypatch,
                                                   tmp_path):
    path = _write(server_module, monkeypatch, tmp_path, connections={
        "bad name!": {"command": "x"},
        "empty": {},
    })
    config = json.loads(path.read_text(encoding="utf-8"))
    assert "bad name!" not in config["mcp"]["servers"]
    assert "empty" not in config["mcp"]["servers"]
    assert _jarvis(config)  # ours survives the mess around it
    assert len(server_module.LAST_CONNECTIONS.problems) == 2


def test_generated_marker_and_permissions(server_module, monkeypatch,
                                          tmp_path):
    import stat as _stat
    path = _write(server_module, monkeypatch, tmp_path)
    body = json.loads(path.read_text(encoding="utf-8"))
    assert "Generated by JARVIS" in body["//"]
    assert path.name == "opencode.json"
    if os.name != "nt":
        # POSIX mode bits are exact; on Windows ACLs govern instead, and
        # there is nothing truthful to assert about them here.
        import stat as _stat
        assert _stat.S_IMODE(os.stat(str(path)).st_mode) == 0o600


def test_rewrite_discards_hand_edits(server_module, monkeypatch, tmp_path):
    home = tmp_path / "home"
    home.mkdir(exist_ok=True)
    path = _write(server_module, monkeypatch, tmp_path)
    path.write_text('{"mcp": {"servers": {"mine": {}}}}', encoding="utf-8")
    _write(server_module, monkeypatch, tmp_path)
    config = json.loads(path.read_text(encoding="utf-8"))
    assert "mine" not in config["mcp"]["servers"]
    assert _jarvis(config)
